function pagntas(varargin)
% pagntas( [...] );
% Agilent Stale
h = timeplot({'AgDevStale','AgDrvStale'}, ...
      'Agilent Stale', ...
      'Stale', ...
      {'AgDevStale','AgDrvStale'}, ...
      varargin{:} );
