function pengas(varargin);
% pengas( [...] );
% Agilent Stale
h = timeplot({'AgDevStale','AgDrvStale'}, ...
      'Agilent Stale', ...
      'Stale', ...
      {'AgDevStale','AgDrvStale'}, ...
      varargin{:} );
